#!/usr/bin/env python3
"""
Garmin Report Generator — 将分析结果生成 Markdown 报告

配合 garmin_analyzer.py 使用，将 FullReport 转为人类可读的 Markdown 文档。

用法:
    from garmin_parser import GarminDataParser
    from garmin_analyzer import GarminAnalyzer
    from garmin_report import GarminReportGenerator

    parser = GarminDataParser("garmin_export.zip")
    dataset = parser.parse_all()
    analyzer = GarminAnalyzer(dataset)
    report = analyzer.generate_full_report()
    generator = GarminReportGenerator(report)
    markdown = generator.generate()
"""

from typing import Optional


# ─── 趋势标记 ──────────────────────────────────────────────

TREND_ICONS = {
    "up": "🔺",
    "down": "🔻",
    "stable": "➡️",
    "anomaly": "⚠️",
}

SEVERITY_ICONS = {
    "critical": "🔴",
    "warning": "🟡",
    "positive": "🟢",
    "info": "🔵",
}

SEVERITY_LABELS = {
    "critical": "严重",
    "warning": "注意",
    "positive": "积极",
    "info": "信息",
}


class GarminReportGenerator:
    """Markdown 报告生成器"""

    def __init__(self, report):
        self.report = report

    def generate(self) -> str:
        """生成完整 Markdown 报告"""
        sections = [
            self._header(),
            self._overall_summary(),
            self._top_insights(),
        ]

        for module in self.report.modules:
            sections.append(self._module_section(module))

        sections.append(self._footer())
        return "\n\n".join(sections)

    def _header(self) -> str:
        """报告头部"""
        user = self.report.user_name
        dr = self.report.data_range
        start = dr.get("start", "N/A")
        end = dr.get("end", "N/A")
        days = dr.get("total_days", "N/A")

        return f"""# Garmin 健康与运动洞察报告
# Garmin Health & Fitness Insight Report

> **用户 / User**: {user}
> **数据范围 / Data Range**: {start} ~ {end}
> **数据天数 / Total Days**: {days}"""

    def _overall_summary(self) -> str:
        """总体评价"""
        return f"""---

## 总体评价 / Overall Summary

{self.report.overall_summary}"""

    def _top_insights(self) -> str:
        """Top 洞察"""
        if not self.report.top_insights:
            return ""

        lines = ["---", "", "## 重点洞察 / Top Insights", ""]

        for i, insight in enumerate(self.report.top_insights, 1):
            icon = SEVERITY_ICONS.get(insight.severity, "ℹ️")
            trend = TREND_ICONS.get(insight.trend, "")
            lines.append(f"### {icon} {insight.summary} {trend}")
            lines.append(f"**{insight.detail}**")
            if insight.recommendation:
                lines.append(f"- 建议: {insight.recommendation}")
            lines.append("")

        return "\n".join(lines)

    def _module_section(self, module) -> str:
        """单个分析模块"""
        lines = [
            "---",
            "",
            f"## {module.title}",
            "",
        ]

        # 数据概况
        lines.append("**数据概况 / Data Overview**")
        for k, v in module.data_overview.items():
            lines.append(f"- {k}: {v}")
        lines.append("")

        # 关键指标表格
        if module.key_metrics:
            lines.append("**关键指标 / Key Metrics**")
            lines.append("")
            lines.append("| 指标 / Metric | 数值 / Value | 单位 / Unit | 趋势 / Trend |")
            lines.append("|---|---|---|---|")
            for m in module.key_metrics:
                trend_icon = TREND_ICONS.get(m.get("trend", "stable"), "")
                lines.append(f"| {m['name']} | {m['value']} | {m.get('unit', '')} | {trend_icon} |")
            lines.append("")

        # 洞察详情
        if module.insights:
            lines.append("**洞察详情 / Insight Details**")
            lines.append("")
            for insight in module.insights:
                icon = SEVERITY_ICONS.get(insight.severity, "ℹ️")
                trend = TREND_ICONS.get(insight.trend, "")
                label = SEVERITY_LABELS.get(insight.severity, "")
                lines.append(f"#### {icon} [{label}] {insight.summary} {trend}")
                lines.append(f"- 当前值: {insight.value_current}")
                if insight.value_previous:
                    lines.append(f"- 对比值: {insight.value_previous}")
                lines.append(f"- 分析: {insight.detail}")
                if insight.recommendation:
                    lines.append(f"- 建议: {insight.recommendation}")
                lines.append("")

        return "\n".join(lines)

    def _footer(self) -> str:
        """报告尾部"""
        return """---

*本报告由 Garmin Data Analyzer Skill 自动生成*
*Generated by Garmin Data Analyzer Skill*

*注意: 本报告仅供参考，不构成医疗建议。如有健康疑虑，请咨询专业医生。*
*Note: This report is for reference only and does not constitute medical advice. Consult a healthcare professional for health concerns.*"""

    def generate_summary(self) -> str:
        """生成简要摘要（用于 AI 快速阅读）"""
        lines = [
            f"用户: {self.report.user_name}",
            f"数据范围: {self.report.data_range.get('start', 'N/A')} ~ {self.report.data_range.get('end', 'N/A')}",
            f"总体评价: {self.report.overall_summary}",
            "",
            "重点洞察:",
        ]

        for i, insight in enumerate(self.report.top_insights, 1):
            icon = SEVERITY_ICONS.get(insight.severity, "")
            lines.append(f"  {i}. {icon} {insight.summary}: {insight.detail}")

        lines.append("")
        lines.append("各模块关键指标:")
        for module in self.report.modules:
            lines.append(f"  [{module.title}]")
            for m in module.key_metrics:
                trend = TREND_ICONS.get(m.get("trend", ""), "")
                lines.append(f"    - {m['name']}: {m['value']} {m.get('unit', '')} {trend}")

        return "\n".join(lines)
